CC = clang
CFLAGS = -Wall -Werror -g

all: listLength listCountOdds listIsSorted listDelete isPalindrome twoSum

listLength: listLength.c
	$(CC) $(CFLAGS) -o listLength listLength.c

listCountOdds: listCountOdds.c
	$(CC) $(CFLAGS) -o listCountOdds listCountOdds.c

listIsSorted: listIsSorted.c
	$(CC) $(CFLAGS) -o listIsSorted listIsSorted.c

listDelete: listDelete.c
	$(CC) $(CFLAGS) -o listDelete listDelete.c

isPalindrome: isPalindrome.c
	$(CC) $(CFLAGS) -o isPalindrome isPalindrome.c

twoSum: twoSum.c
	$(CC) $(CFLAGS) -o twoSum twoSum.c


##############################################################################

clean:
	rm -f listLength listCountOdds listIsSorted listDelete isPalindrome twoSum
